<div class="hbr-main pad-main">
<div class="block-title-main">
<h2>V4U OwlCarousel Slider</h2>
<div class="title-border"></div>
</div>
<div class="hbr-main">
<div style="margin: 0 -10px;">
<div class="hbr-content hbr-slider">
<div class="hbr-inner"><img src="pub/static/frontend/Wizdom/CustomTheme/en_US/images/instagram-img-01.jpg" alt="" /></div>
<div class="hbr-inner"><img src="pub/static/frontend/Wizdom/CustomTheme/en_US/images/instagram-img-02.jpg" alt="" /></div>
<div class="hbr-inner"><img src="pub/static/frontend/Wizdom/CustomTheme/en_US/images/instagram-img-03.jpg" alt="" /></div>
<div class="hbr-inner"><img src="pub/static/frontend/Wizdom/CustomTheme/en_US/images/instagram-img-04.jpg" alt="" /></div>
<div class="hbr-inner"><img src="pub/static/frontend/Wizdom/CustomTheme/en_US/images/instagram-img-05.jpg" alt="" /></div>
<div class="hbr-inner"><img src="pub/static/frontend/Wizdom/CustomTheme/en_US/images/instagram-img-06.jpg" alt="" /></div>
<div class="hbr-inner"><img src="pub/static/frontend/Wizdom/CustomTheme/en_US/images/instagram-img-07.jpg" alt="" /></div>
</div>
</div>
<script type="text/javascript" xml="space">// <![CDATA[
            require(['jquery', 'cpowlcarousel'], function ($) {
                jQuery(document).ready(function () {
                    jQuery(".hbr-slider").owlCarousel({
                        items: 5,
                        itemsDesktop: [1080, 4],
                        itemsDesktopSmall: [860, 3],
                        itemsTablet: [768, 3],
                        itemsTabletSmall: [639, 3],
                        itemsMobile: [479, 2],
                        pagination: false,
                        navigationText: ['<div class="lft-btn"><i class="fa fa-angle-left"></i></div>', '<div class="rgt-btn"><i class="fa fa-angle-right"></div>'],
                        navigation: true,
                    });
                });
            });
// ]]></script>
</div>
</div>